server:
  port: 8888

spring:
  datasource:
    url: jdbc:sqlite:./database.db
    username: root
    password: root
    driver-class-name: org.sqlite.JDBC

chopperbot:
  proxy:
    enable: 0
    address: 127.0.0.1
    port: 7890
  plugin:
    title-generate-plugin:
      handler: ${TITLE-GENERATE-PLUGIN-HANDLER:GptTitleGenerator}
    label-generate-plugin:
      handler: ${LABEL-GENERATE-PLUGIN-HANDLER:GptLabelGenerator}
